config/routes.rb
TasMongo::Application.routes.draw do

  

  namespace :admin do
    get "/", :to => 'admin#index'
    
    get "/pages", :to => 'pages#index'
    
    get "/pages/new",   :to => 'pages#new'
    get "/pages/:slug", :to => 'pages#show', :as => 'page'
    get "/pages/:slug/edit", :to => 'pages#edit', :as => 'edit_page'

    post "/pages",      :to => 'pages#create'
    put    "/pages/:slug", :to => 'pages#update'
    delete "/pages/:slug", :to => 'pages#destroy'
    
  end

  devise_for :users

  root :to => 'site#index'

  get   "/:slug", :to => 'site#show_page', :as => 'show_page'

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset
  include Ckeditor::Orm::Mongoid::AssetBase
              
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  
  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/page.rb
class Page
  include Mongoid::Document

  before_create { generate_slug }

  field :title, type: String
  field :body, type: String
  field :parent_page_slug, type: String
  field :slug, type: String



  # Parent serviceline of current serviceline if set
  def parent
    Page.find_by(slug: self.parent_page_slug) if self.parent_page_slug.present?
  end


  # Find the servicelines that would qualify to be parents of the current serviceline
  def availableParents

    available_pages = Page.where(:slug.ne => self.slug) if self.slug.present?
    available_pages = Page.all if !self.slug.present?

    valid_pages = []

    if available_pages
      available_pages.each do |sl|
        
        if sl.validHeirachy(self)
          valid_pages << [sl.title, sl.slug]
        end
    
      end
    end

    valid_pages
  end


  # Check if the provided serviceline qualifies as a valid parent without causing and infinite loop
  def validHeirachy(original)
    if self.parent.present? && self.parent.slug != original.slug
      self.parent.validHeirachy(original)
    elsif self.parent.present? && self.parent.slug == original.slug
      false
    else 
      true
    end
  end



  def generate_slug
    new_slug = self.title.parameterize.to_s

    # Check if the new slug already exists
    count = 0
    while Page.where(slug: new_slug).first
      count = count + 1
      new_slug = self.title.parameterize + "-" + count.to_s
      puts "Slug Exists: New version = " + new_slug.to_s
    end    

    self.slug = new_slug
  end  

end

app/models/site.rb
class Site
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
  field :home_page_slug, type: String
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController

  layout "admin-without-sidebar"

  def index



  end

end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::AdminController
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find_by(slug: params[:slug])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find_by(slug: params[:slug])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to admin_page_path(@page.slug), notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find_by(slug: params[:slug])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to admin_page_path(@page.slug), notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find_by(slug: params[:slug])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to admin_pages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index

    @site = Site.first

    if !@site 
      # The website has not been generated yet, so lets create a blank one.
      generate_new_website
    end

    @page = Page.find_by(slug: @site.home_page_slug)

  end



  def show_page

    @page = Page.find_by(slug: params[:slug])

  end



private
    
  # No website already exists, so we'll generate a quick skeleton and then direct the user to make changes
  def generate_new_website

    page = Page.new 
    page.title = "Homepage"
    page.body = "Welcome to my homepage"
    page.save

    site = Site.new
    site.name = "New Website"
    site.description = "Welcome to my brand new website"
    site.home_page_slug = page.slug
    site.save

    index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/admin/admin/index.html.slim
h1 Website Admin


h2 Pages
= link_to "pages", admin_pages_path

app/views/admin/pages/_form.html.slim
= simple_form_for @page, :url => admin_page_path(@page.slug) do |f|
  
  - if @page.errors.any?
    #error_explanation
      h2 = "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      ul
        - @page.errors.full_messages.each do |message|
          li = message

  .field
    = f.label "Page Title"
    = f.text_field :title, :class => 'full'

  .field
    = f.label "Page Slug"
    = f.text_field :slug    

  .field
    = f.label "Parent Page"
    - available_parents = @page.availableParents
    = select('page', 'parent_page_slug', available_parents, {}, :selected => @page.parent_page_slug )
    
  .field
    = f.text_area :body, :class => :ckeditor, :rows => 1000
  

  .actions 
    = f.submit 'Save'
    = button_to "Cancel", admin_pages_path

app/views/admin/pages/edit.html.slim
h1 Editing #{@page.title}

== render 'form'

= link_to 'Show', admin_page_path(@page.slug)
'|
= link_to 'Back', admin_pages_path

app/views/admin/pages/index.html.slim
h1 Listing pages

table
  tr
    th Title
    th Parent page
    th Slug
    th
    th
    th

  - @pages.each do |page|
    tr
      td = page.title
      td = page.parent_page_slug
      td = page.slug
      td = link_to 'Visit Page', show_page_path(page.slug)
      td = link_to 'Edit Page', admin_edit_page_path(page.slug)
      / td = button_to 'Destroy', admin_page_path(page.slug), :confirm => 'Are you sure?', :method => :delete

br

/ = link_to 'New Page', new_admin_page_path

app/views/admin/pages/new.html.slim
h1 New page

= form_for @page, :url => admin_pages_path do |f|
  - if @page.errors.any?
    #error_explanation
      h2 = "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      ul
        - @page.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :parent_page_slug
    = f.number_field :parent_page_slug
  
  .actions = f.submit 'Save'


= link_to 'Back', admin_pages_path

app/views/admin/pages/show.html.slim
p#notice = notice

.page
  = raw(@page.body)


= link_to 'Edit', admin_edit_page_path(@page.slug)
'|
= link_to 'Back', admin_pages_path

app/views/layouts/admin-without-sidebar.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TasMongo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" , '/assets/ckeditor/ckeditor.js', '/assets/ckeditor/init.js'%>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
    CKEDITOR.config.height = 400;
  </script>
</head>
<body class="admin-without-sidebar">

  <div id="container">
    
    <div id="header">
      Her eis the header
    </div>

    <div id="content">
      <%= yield %>
    </div>

    <div id="footer">
      here is the admins footer
    </div>

  </div>

</body>
</html>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TasMongo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" , '/assets/ckeditor/ckeditor.js', '/assets/ckeditor/init.js'%>
  <%= csrf_meta_tags %>
</head>
<body class="admin">

  <div id="container">
    
    <div id="header">
      Her eis the header
    </div>

    <div id="content">
      <%= yield %>
    </div>

    <div id="footer">
      here is the admin footer
    </div>

  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TasMongo</title>
  <%= stylesheet_link_tag "site", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="container">

  <%= yield %>
  
</body>
</html>

app/views/site/index.html.slim
h1 = @site.name

app/views/site/show_page.slim
h1 = @page.title